import jsPDF from "jspdf";

export const generatePDF = (result, imageFile) => {
    const doc = new jsPDF();
    const { diagnosis } = result;

    // Naslov klinike
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("BioScan Medical Report", 105, 20, null, null, "center");

    // Uključivanje slike
    if (imageFile) {
        const img = new Image();
        img.src = URL.createObjectURL(imageFile);
        doc.addImage(img, "JPEG", 10, 30, 60, 60); // Slika u gornjem levom uglu
    }

    // Informacije o dijagnozi
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(`Diagnosis: ${diagnosis}`, 80, 50);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);

    // Detaljan opis baziran na dijagnozi
    let details = "";
    let recommendations = "";

    switch (diagnosis) {
        case "Normal":
            details =
                "No abnormalities were detected in the uploaded image. This indicates that your current condition is healthy.";
            recommendations =
                "Maintain a balanced diet, exercise regularly, and attend regular health checkups.";
            break;
        case "Cyst":
            details =
                "A cyst has been detected. Cysts are typically fluid-filled sacs that may require further evaluation.";
            recommendations =
                "Consult with a medical specialist to determine the nature and potential treatment for the cyst.";
            break;
        case "Stone":
            details =
                "A stone has been detected. Stones can occur in various organs, often causing discomfort or other symptoms.";
            recommendations =
                "Consider discussing treatment options with a healthcare provider. Stay hydrated and monitor symptoms closely.";
            break;
        case "Tumor":
            details =
                "A tumor has been detected. Tumors can be benign or malignant, requiring immediate medical attention.";
            recommendations =
                "Consult with an oncologist or a specialist immediately to determine the nature and appropriate treatment.";
            break;
        default:
            details = "Unknown diagnosis. Please consult a medical professional.";
            recommendations =
                "Ensure the image is clear and retry or contact BioScan for support.";
            break;
    }

    doc.text(`Details: ${details}`, 10, 100, { maxWidth: 190 });
    doc.text(`Recommendations: ${recommendations}`, 10, 140, { maxWidth: 190 });

    // Footer
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.text("This report is auto-generated by BioScan", 105, 280, null, null, "center");

    // Generisanje PDF-a
    doc.save(`BioScan_Report_${diagnosis}.pdf`);
};
